name: Direct Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'src/tokens.ts'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build project
        run: npm run build
        
      - name: Debug build output
        run: |
          echo "Build directory contents:"
          ls -la build || echo "Build directory not found"
          
          # List all generated files
          echo "All generated files:"
          find build -type f -name "*.js" -o -name "*.css" | head -20
      
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build
          clean: false
