name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'src/tokens.ts'
      - 'dimension.css'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install
        
      - name: Build project
        run: npm run build
      
      - name: Deploy to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build # Adjust if your build output is in a different folder
          # Only deploy files that would contain updated tokens
          clean: false # Don't remove existing files in gh-pages branch
