name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Basic permissions needed
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: |
          npm run build
          touch build/.nojekyll
        env:
          PUBLIC_URL: "https://jennifer-nguyenn.github.io/codedemo"
          
      # Using peaceiris action instead of JamesIves
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./build
          force_orphan: true
          commit_message: "Deploy to GitHub Pages"
