name: Transform Design Tokens
on:
  push:
    branches:
      - main
    paths:
      - 'src/generated-tokens.js/**'
jobs:
  transform-tokens:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Transform tokens
        run: node scripts/transform-tokens.js
      
      - name: Commit changes
        id: commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          if [[ -n $(git status -s) ]]; then
            git add -A
            git commit -m "Update design tokens from Supernova"
            git push
            echo "changes_made=true" >> $GITHUB_OUTPUT
            echo "✅ Changes committed and pushed"
          else
            echo "changes_made=false" >> $GITHUB_OUTPUT
            echo "ℹ️ No changes to commit"
          fi
          
          # Debug - print the value to see what's being set
          echo "Output value: $(cat $GITHUB_OUTPUT)"
      
      # Force trigger the deployment workflow for tokens.ts changes
      - name: Force deployment trigger
        if: steps.commit.outputs.changes_made == 'true'
        run: |
          echo "Changes made: ${{ steps.commit.outputs.changes_made }}"
          echo "Ensuring deployment is triggered..."
          # Touch the tokens file to update its timestamp
          touch src/styles/tokens.ts
          git add src/styles/tokens.ts
          git commit -m "Trigger deployment workflow [skip ci]"
          git push
      
      # Add a step that runs even if no changes need deployment
      - name: No changes detected
        if: steps.commit.outputs.changes_made != 'true'
        run: echo "No changes detected, skipping deployment trigger"
